language: ruby
rvm:
- 2.5.3
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- rubocop
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false